### ISSUE TITLE
Request for Project Documentation

### ISSUE THREAD

**Issue by m-yahya** [dvrosalesm/energy-did#1]
I’ve been reviewing your project and noticed that the `README` file is not fully updated and no other documentation is available. This makes it difficult to understand the project structure, especially how to install and run it, and what its features are.

Could you please update the `README` file with the following information:

## Introduction
Briefly describe the project, its purpose, and its functionality.

## Features
List the main features of your project.

## Installation
Provide detailed instructions on how to install the project.

## Usage
Explain how to use the project after installation. Include examples if possible.

**Comment by dvrosalesm** [comment]
Hi! Thanks for the feedback, I've added the required documentation to the projects README file. Let me know if theres any improvement that you would like to see.

Sorry for the delay, I don't get notifications for personal repositories from Github and only today I noticed that there was an open issue, thanks to Jen since he pointed it out.

**Comment by m-yahya** [comment]
Dear Diego,

Thank you very much for updating the documentation. As there was no Pull Request available for review, I have cloned the project and tested it locally.

I am pleased that the following features are functioning:
- Create a full DID
- Mint asset NFT
- Create claims and request attestation
- Create claims and request attestation
- Attest claim
- Request verification
- Verify credentials

I would like to appreciate you on the following aspects of the project:
- Separation of concerns: the project structure separates different aspects into distinct directories (`asset-manager`, `attester-cli`, `attester-manager`, `contracts`, `kilt-common`, and `verifier-cli`).
- Modularity: The project has been organized into modules or packages, each focusing on a specific functionality. 

However, I have identified a few areas that could benefit from further improvement:
- Documentation enhancement: To enhance the project's usability, kindly consider adding comprehensive documentation on how to create a full DID.
- Enhancing command execution: I observed that the command `yarn --cwd ./contracts` appears to be non-functional. A recommended improvement is to execute the command `npx hardhat run ./scripts/deploy.ts --network sepolia` from within the `contracts` directory to ensure its proper execution. For context, when running this command, it currently initializes a new Hardhat project instead of deploying the `contract`.
- Secure configuration handling: You may consider loading sensitive environment variables such as `API_KEY` and `ACCOUNT_PRIVATE_KEY` from a secure `.env` file to enhance security and manageability.
- Addressing Warnings: During my assessment, I encountered certain warning messages, including:
    - `Property 'claim' does not exist on type 'object'` 
    - `Type 'string' is not assignable to type '"`. 
    - . . .

  You may further investigate and resolve these warnings to maintain code quality. 
  
  Thank you once again for your contribution to the project. Your efforts are greatly appreciated.
  Bests,

**Comment by dvrosalesm** [comment]
Hi @m-yahya , 

I just submitted a [new PR](https://github.com/dvrosalesm/energy-did/pull/2) addressing the issues, 

- Documentation enhancements: I added an extended description of Full DIDs and added a screenshare example of the usage.
- Secure configuration: Looks like I forgot to create an .env file with all the secrets for the contracts project, to fix and further improve the solution I centralized all the .env secrets in a single file at the root level of the project so I can share it between apps, I also updated the documentation, now the sequence of commands should work to deploy and mint the power asset.
- Addressing warnings: Done, I resolved the typing warnings and a few ts compiler incongruences as well. 

Thanks for the great feedback,
All the best,

**Comment by dvrosalesm** [comment]
Resolved

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
AmeanAsad, @block-0x, @heipacker, @code342, @lehuuhieu7777, @howeverforever, @jacob-chia, @insulineru, @mgcrea, @teon, @irishmaestro, @alexkorol, @Oyelowo, @daweth, @Redster, @dariaag, @iouae, @ghu, @tahmed5, @franklee00, @mmacedoeu, @usdelys, @kazuakiishiguro, @Fiskantes, @wniter, @avalidurl, @fiveakatto, @solidityslayer, @lucadonnoh, @0xd3gen, @DoTheBestToGetTheBest, @sekmet, @CPerezz, @19-xiaogao, @0xrjman, @mthli, @0xhatsume, @bretth18, @0xF7A4C6, @xiongmaofeifei666, @mxssl, @0xShack, @amlcodes, @pyropy, @hack3r-0m, @Nuttymoon, @zoakes, @codieboomboom, @BraedenNorris, @ibaddesmukh
